export const industryOptions = [
  { value: '01', cnLabel: '金融服务', enLabel: 'Financial services' },
  { value: '02', cnLabel: '广告/传媒/市场', enLabel: 'Advertising/Marketing/PR' },
  { value: '03', cnLabel: '航空/航天', enLabel: 'Aerospace/Aviation' },
  { value: '04', cnLabel: '农业', enLabel: 'Agriculture' },
  { value: '05', cnLabel: '银行', enLabel: 'Banking' },
  { value: '06', cnLabel: '生物/制药', enLabel: 'Biotechnology/Pharmaceuticals' },
  { value: '07', cnLabel: '建筑', enLabel: 'Construction' },
  { value: '08', cnLabel: '咨询', enLabel: 'Consulting' },
  { value: '09', cnLabel: '消费品/零售', enLabel: 'Consumer Products/Retail' },
  { value: '10', cnLabel: '教育', enLabel: 'Education' },
  { value: '11', cnLabel: '能源/公共设施', enLabel: 'Energy/Utilities' },
  { value: '12', cnLabel: '工程', enLabel: 'Engineering' },
  { value: '13', cnLabel: '娱乐/休闲', enLabel: 'Entertainment/Hospitality/Leisure' },
  { value: '14', cnLabel: '环境服务', enLabel: 'Environmental Services' },
  { value: '15', cnLabel: '会计', enLabel: 'Accounting' },
  { value: '16', cnLabel: '政府', enLabel: 'Government' },
  { value: '17', cnLabel: '健康服务', enLabel: 'Health Care' },
  { value: '18', cnLabel: '人力资源', enLabel: 'Human Resources/Recruiting' },
  { value: '19', cnLabel: '保险', enLabel: 'Insurance' },
  { value: '20', cnLabel: 'IT/计算机', enLabel: 'Information Technology / IT Services' },
  { value: '21', cnLabel: '法律服务', enLabel: 'Legal Services' },
  { value: '22', cnLabel: '制造业', enLabel: 'Manufacturing' },
  { value: '23', cnLabel: '媒体/出版', enLabel: 'Media/Publishing' },
  { value: '24', cnLabel: '军队/防务承包', enLabel: 'Military/Defense Contracting' },
  { value: '25', cnLabel: '采矿', enLabel: 'Mining' },
  { value: '26', cnLabel: '非营利机构', enLabel: 'Nonprofit' },
  { value: '27', cnLabel: '专业服务', enLabel: 'Professional Services' },
  { value: '28', cnLabel: '地产', enLabel: 'Real Estate' },
  { value: '29', cnLabel: '技术/通信', enLabel: 'Technology/Telecommunications' },
  { value: '30', cnLabel: '运输/物流', enLabel: 'Transport/Logistics' },
]
