export const PDF_TEMPLATE_PATH = '/templates/gvip-application-form.pdf'
export const PDF_TEMPLATE_FONT_PATH = '/fonts/simhei.ttf'

export const PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX = 2

export const pdfFieldMap = [
  {
    key: 'personalInfo.cnName',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.245,
    yRatio: 0.282,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'personalInfo.enName',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.57,
    yRatio: 0.282,
    fontSize: 10.8,
    maxWidth: 130,
  },
  {
    key: 'personalInfo.gender',
    type: 'radio',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    mark: '✓',
    options: {
      male: { xRatio: 0.247, yRatio: 0.318 },
      female: { xRatio: 0.363, yRatio: 0.318 },
      男: { xRatio: 0.247, yRatio: 0.318 },
      女: { xRatio: 0.363, yRatio: 0.318 },
    },
    fontSize: 10,
  },
  {
    key: 'personalInfo.dateOfBirth',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.62,
    yRatio: 0.314,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'personalInfo.nationality',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.22,
    yRatio: 0.35,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'personalInfo.countryOfBirth',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.62,
    yRatio: 0.35,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'personalInfo.idDocumentType',
    type: 'radio',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    mark: '✓',
    options: {
      'national-id': { xRatio: 0.207, yRatio: 0.429 },
      passport: { xRatio: 0.338, yRatio: 0.429 },
      'travel-permit': { xRatio: 0.617, yRatio: 0.429 },
      other: { xRatio: 0.788, yRatio: 0.429 },
      身份证: { xRatio: 0.207, yRatio: 0.429 },
      护照: { xRatio: 0.338, yRatio: 0.429 },
      港澳台居民来往大陆通行证: { xRatio: 0.617, yRatio: 0.429 },
      其他: { xRatio: 0.788, yRatio: 0.429 },
    },
    fontSize: 10,
  },
  {
    key: 'personalInfo.idDocumentOther',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.835,
    yRatio: 0.425,
    fontSize: 10.2,
    maxWidth: 110,
  },
  {
    key: 'personalInfo.idNumber',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.255,
    yRatio: 0.473,
    fontSize: 10.2,
    maxWidth: 500,
  },
  {
    key: 'personalInfo.hasUsVisa',
    type: 'radio',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    mark: '✓',
    options: {
      yes: { xRatio: 0.415, yRatio: 0.522 },
      no: { xRatio: 0.505, yRatio: 0.522 },
      是: { xRatio: 0.415, yRatio: 0.522 },
      否: { xRatio: 0.505, yRatio: 0.522 },
    },
    fontSize: 10,
  },
  {
    key: 'personalInfo.visaExpirationDate',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.815,
    yRatio: 0.508,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'personalInfo.workPhone',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.33,
    yRatio: 0.56,
    fontSize: 10.8,
    maxWidth: 150,
  },
  {
    key: 'personalInfo.mobilePhone',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.77,
    yRatio: 0.56,
    fontSize: 10.8,
    maxWidth: 150,
  },
  {
    key: 'personalInfo.email',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.21,
    yRatio: 0.598,
    fontSize: 10.2,
    maxWidth: 180,
  },
  {
    key: 'personalInfo.address',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.53,
    yRatio: 0.598,
    fontSize: 10.2,
    maxWidth: 360,
  },
  {
    key: 'personalInfo.clothingSize',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.275,
    yRatio: 0.636,
    fontSize: 10.8,
    maxWidth: 80,
  },
  {
    key: 'personalInfo.linkedin',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.745,
    yRatio: 0.636,
    fontSize: 10.2,
    maxWidth: 180,
  },
  {
    key: 'contactPerson.cnName',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.245,
    yRatio: 0.76,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'contactPerson.enName',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.57,
    yRatio: 0.76,
    fontSize: 10.8,
    maxWidth: 130,
  },
  {
    key: 'contactPerson.gender',
    type: 'radio',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    mark: '✓',
    options: {
      male: { xRatio: 0.247, yRatio: 0.828 },
      female: { xRatio: 0.363, yRatio: 0.828 },
      男: { xRatio: 0.247, yRatio: 0.828 },
      女: { xRatio: 0.363, yRatio: 0.828 },
    },
    fontSize: 10,
  },
  {
    key: 'contactPerson.relationship',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.625,
    yRatio: 0.795,
    fontSize: 10.8,
    maxWidth: 120,
  },
  {
    key: 'contactPerson.mobilePhone',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.355,
    yRatio: 0.848,
    fontSize: 10.8,
    maxWidth: 150,
  },
  {
    key: 'contactPerson.email',
    page: PDF_TEMPLATE_BASIC_FACTS_PAGE_INDEX,
    xRatio: 0.745,
    yRatio: 0.848,
    fontSize: 10.2,
    maxWidth: 170,
  },
]
